"""Source discovery and initial phase-aware file enumeration."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from eu5miner.paths import resolve_install_path


class ContentPhase(StrEnum):
    """Known EU5 content loading phases."""

    LOADING_SCREEN = "loading_screen"
    MAIN_MENU = "main_menu"
    IN_GAME = "in_game"


@dataclass(frozen=True)
class GameInstall:
    """Discovered structure for a local EU5 installation."""

    root: Path
    game_dir: Path
    dlc_dir: Path
    mod_dir: Path

    @classmethod
    def discover(cls, root: str | Path | None = None) -> GameInstall:
        install_root = resolve_install_path(root)
        game_dir = install_root / "game"
        dlc_dir = game_dir / "dlc"
        mod_dir = game_dir / "mod"

        required_paths = [
            install_root,
            game_dir,
            game_dir / ContentPhase.LOADING_SCREEN.value,
            game_dir / ContentPhase.MAIN_MENU.value,
            game_dir / ContentPhase.IN_GAME.value,
        ]
        missing = [path for path in required_paths if not path.exists()]
        if missing:
            missing_text = ", ".join(str(path) for path in missing)
            raise FileNotFoundError(f"EU5 install is missing expected paths: {missing_text}")

        return cls(root=install_root, game_dir=game_dir, dlc_dir=dlc_dir, mod_dir=mod_dir)

    def phase_dir(self, phase: ContentPhase) -> Path:
        return self.game_dir / phase.value

    def iter_phase_files(
        self,
        phase: ContentPhase,
        relative_subpath: str | Path = "",
    ) -> list[Path]:
        base_dir = self.phase_dir(phase)
        search_root = base_dir / Path(relative_subpath)
        if not search_root.exists():
            return []
        return sorted(path for path in search_root.rglob("*") if path.is_file())

    def representative_files(self) -> dict[str, Path]:
        return {
            "events_readme": self.phase_dir(ContentPhase.IN_GAME) / "events" / "readme.txt",
            "event_sample": self.phase_dir(ContentPhase.IN_GAME) / "events" / "civil_war.txt",
            "mission_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "missions"
            / "____Info.txt",
            "mission_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "missions"
            / "generic_conquer_province_mission_pack.txt",
            "situation_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "situations"
            / "readme.txt",
            "situation_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "situations"
            / "black_death.txt",
            "disaster_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "disasters"
            / "english_civil_war.txt",
            "customizable_localization_info": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "customizable_localization"
            / "customizable_localization.info",
            "customizable_localization_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "customizable_localization"
            / "00_customizable_localization.txt",
            "effect_localization_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "effect_localization"
            / "country_effects.txt",
            "trigger_localization_info": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "trigger_localization"
            / "_trigger_localization.info",
            "trigger_localization_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "trigger_localization"
            / "country_triggers.txt",
            "english_effects_localization": self.phase_dir(ContentPhase.MAIN_MENU)
            / "localization"
            / "english"
            / "effects_l_english.yml",
            "english_triggers_localization": self.phase_dir(ContentPhase.MAIN_MENU)
            / "localization"
            / "english"
            / "triggers_l_english.yml",
            "english_laws_localization": self.phase_dir(ContentPhase.MAIN_MENU)
            / "localization"
            / "english"
            / "laws_and_policies_l_english.yml",
            "scripted_trigger": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "scripted_triggers"
            / "country_triggers.txt",
            "scripted_effect": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "scripted_effects"
            / "country_effects.txt",
            "scripted_modifier_info": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "scripted_modifiers"
            / "scripted_modifiers.info",
            "scripted_list_info": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "scripted_lists"
            / "scripted_lists.info",
            "scripted_list_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "scripted_lists"
            / "country_lists.txt",
            "scripted_relation_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "scripted_relations"
            / "readme.txt",
            "scripted_relation_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "scripted_relations"
            / "alliance.txt",
            "scripted_relation_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "scripted_relations"
            / "trade_access.txt",
            "casus_belli_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "casus_belli"
            / "conquest.txt",
            "casus_belli_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "casus_belli"
            / "00_hardcoded.txt",
            "casus_belli_dense_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "casus_belli"
            / "coalition.txt",
            "casus_belli_subject_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "casus_belli"
            / "make_tributary_cb.txt",
            "casus_belli_religious_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "casus_belli"
            / "religious_superiority.txt",
            "casus_belli_trade_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "casus_belli"
            / "trade_conflict.txt",
            "peace_treaty_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "peace_treaties"
            / "readme.txt",
            "peace_treaty_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "peace_treaties"
            / "humiliate.txt",
            "peace_treaty_select_trigger_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "peace_treaties"
            / "steal_maps_treaty.txt",
            "peace_treaty_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "peace_treaties"
            / "force_tributary.txt",
            "peace_treaty_special_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "peace_treaties"
            / "religious_supremacy.txt",
            "peace_treaty_exclusive_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "peace_treaties"
            / "dismantle_fort.txt",
            "subject_type_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "subject_types"
            / "readme.txt",
            "subject_type_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "subject_types"
            / "vassal.txt",
            "subject_type_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "subject_types"
            / "tributary.txt",
            "subject_type_colonial_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "subject_types"
            / "colonial_nation.txt",
            "subject_type_hre_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "subject_types"
            / "hre.txt",
            "subject_type_special_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "subject_types"
            / "appanage.txt",
            "subject_military_stance_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "subject_military_stances"
            / "readme.txt",
            "subject_military_stance_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "subject_military_stances"
            / "00_default.txt",
            "country_interaction_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "country_interactions"
            / "readme.txt",
            "country_interaction_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "country_interactions"
            / "request_loan.txt",
            "country_interaction_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "country_interactions"
            / "sell_icon.txt",
            "character_interaction_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "character_interactions"
            / "readme.txt",
            "character_interaction_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "character_interactions"
            / "abdicate.txt",
            "character_interaction_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "character_interactions"
            / "move_children_to_court.txt",
            "character_interaction_ui_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "character_interactions"
            / "marry_noble.txt",
            "unit_type_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_types"
            / "readme.txt",
            "unit_type_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_types"
            / "0_knights.txt",
            "unit_type_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_types"
            / "2_conquistador.txt",
            "unit_ability_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_abilities"
            / "readme.txt",
            "unit_ability_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_abilities"
            / "drill_army.txt",
            "unit_ability_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_abilities"
            / "scorch_earth.txt",
            "unit_category_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_categories"
            / "readme.txt",
            "unit_category_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_categories"
            / "00_army_infantry.txt",
            "unit_category_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "unit_categories"
            / "14_navy_transport.txt",
            "government_type_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "government_types"
            / "00_default.txt",
            "government_reform_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "government_reforms"
            / "readme.txt",
            "government_reform_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "government_reforms"
            / "common.txt",
            "government_reform_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "government_reforms"
            / "monarchy.txt",
            "government_reform_special_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "government_reforms"
            / "country_specific.txt",
            "law_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "laws"
            / "readme.txt",
            "law_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "laws"
            / "01_common.txt",
            "law_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "laws"
            / "00_monarchy.txt",
            "law_country_specific_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "laws"
            / "02_country_specific.txt",
            "law_io_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "laws"
            / "20_middle_kingdom.txt",
            "law_io_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "laws"
            / "20_hre.txt",
            "policy_info": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "policies"
            / "policies.info",
            "estate_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "estates"
            / "00_default.txt",
            "estate_privilege_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "estate_privileges"
            / "readme.txt",
            "estate_privilege_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "estate_privileges"
            / "burghers_estate.txt",
            "estate_privilege_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "estate_privileges"
            / "clergy_estate.txt",
            "estate_privilege_special_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "estate_privileges"
            / "nobles_estate.txt",
            "parliament_type_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_types"
            / "readme.txt",
            "parliament_type_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_types"
            / "00_default.txt",
            "parliament_type_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_types"
            / "01_international_organization.txt",
            "parliament_agenda_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_agendas"
            / "readme.txt",
            "parliament_agenda_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_agendas"
            / "00_common.txt",
            "parliament_agenda_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_agendas"
            / "01_societal_values.txt",
            "parliament_agenda_special_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_agendas"
            / "10_hre_agendas.txt",
            "parliament_issue_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_issues"
            / "readme.txt",
            "parliament_issue_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_issues"
            / "02_crown_estate_parliament_issues.txt",
            "parliament_issue_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_issues"
            / "03_nobles_estate_parliament_issues.txt",
            "parliament_issue_special_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "parliament_issues"
            / "10_hre_issues.txt",
            "institution_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "institution"
            / "readme.txt",
            "institution_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "institution"
            / "age_1_traditions_institutions.txt",
            "institution_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "institution"
            / "age_4_reformation_institutions.txt",
            "holy_site_type_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "holy_site_types"
            / "readme.txt",
            "holy_site_type_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "holy_site_types"
            / "00_holy_site_types.txt",
            "holy_site_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "holy_sites"
            / "readme.txt",
            "holy_site_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "holy_sites"
            / "catholic.txt",
            "holy_site_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "holy_sites"
            / "hindu.txt",
            "societal_value_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "societal_values"
            / "00_default.txt",
            "religious_aspect_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_aspects"
            / "readme.txt",
            "religious_aspect_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_aspects"
            / "common.txt",
            "religious_aspect_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_aspects"
            / "protestant.txt",
            "religious_faction_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_factions"
            / "readme.txt",
            "religious_faction_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_factions"
            / "shinto.txt",
            "religious_focus_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_focuses"
            / "readme.txt",
            "religious_focus_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_focuses"
            / "nahuatl.txt",
            "religious_school_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_schools"
            / "sunni.txt",
            "religious_school_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_schools"
            / "hinduism.txt",
            "religious_figure_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_figures"
            / "00_muslim.txt",
            "religious_figure_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religious_figures"
            / "01_hindu.txt",
            "wargoal_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "wargoals"
            / "readme.txt",
            "wargoal_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "wargoals"
            / "00_default.txt",
            "on_action_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "on_action"
            / "religion_flavor_pulse.txt",
            "on_action_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "on_action"
            / "character_death_pulses.txt",
            "on_action_hardcoded_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "on_action"
            / "_hardcoded.txt",
            "script_value_info": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "script_values"
            / "_script_values.info",
            "script_value_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "script_values"
            / "best_capital_for_colony.txt",
            "script_value_scalar_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "script_values"
            / "eu4_conversions.txt",
            "building_type_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "building_types"
            / "readme.txt",
            "building_type_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "building_types"
            / "common_buildings.txt",
            "building_type_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "building_types"
            / "capital_buildings.txt",
            "building_category_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "building_categories"
            / "00_default.txt",
            "goods_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "goods"
            / "readme.txt",
            "goods_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "goods"
            / "00_raw_materials.txt",
            "goods_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "goods"
            / "03_food.txt",
            "price_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "prices"
            / "readme.txt",
            "price_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "prices"
            / "00_hardcoded.txt",
            "price_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "prices"
            / "01_buildings.txt",
            "goods_demand_category_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "goods_demand_category"
            / "00_default.txt",
            "goods_demand_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "goods_demand"
            / "building_construction_costs.txt",
            "goods_demand_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "goods_demand"
            / "pop_demands.txt",
            "goods_demand_tertiary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "goods_demand"
            / "from_events.txt",
            "production_method_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "production_methods"
            / "__readme.txt",
            "production_method_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "production_methods"
            / "unsorted_building_inputs.txt",
            "employment_system_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "employment_systems"
            / "readme.txt",
            "employment_system_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "employment_systems"
            / "00_default.txt",
            "generic_action_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "generic_actions"
            / "readme.txt",
            "generic_action_market_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "generic_actions"
            / "markets.txt",
            "generic_action_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "generic_actions"
            / "employment_system.txt",
            "generic_action_loan_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "generic_actions"
            / "take_bank_loan.txt",
            "attribute_column_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "attribute_columns"
            / "readme.txt",
            "attribute_column_default_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "attribute_columns"
            / "00_defaults.txt",
            "attribute_column_market_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "attribute_columns"
            / "19_market.txt",
            "attribute_column_trade_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "attribute_columns"
            / "29_trade.txt",
            "attribute_column_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "attribute_columns"
            / "31_goods.txt",
            "attribute_column_loan_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "attribute_columns"
            / "40_loan.txt",
            "culture_info": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "cultures"
            / "00_cultures.info",
            "culture_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "cultures"
            / "british.txt",
            "religion_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religions"
            / "christian.txt",
            "religion_secondary_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "religions"
            / "buddhist.txt",
            "country_description_category_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "country_description_categories"
            / "readme.txt",
            "country_description_category_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "common"
            / "country_description_categories"
            / "categories.txt",
            "setup_country_readme": self.phase_dir(ContentPhase.IN_GAME)
            / "setup"
            / "countries"
            / "00_readme.info",
            "setup_country_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "setup"
            / "countries"
            / "france.txt",
            "gui_sample": self.phase_dir(ContentPhase.IN_GAME) / "gui" / "agenda_view.gui",
            "gui_types_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "gui"
            / "eventwindow.gui",
            "gui_library_sample": self.phase_dir(ContentPhase.IN_GAME)
            / "gui"
            / "ui_library.gui",
            "main_menu_scenarios_sample": self.phase_dir(ContentPhase.MAIN_MENU)
            / "common"
            / "scenarios"
            / "00_scenarios.txt",
            "main_menu_country_setup_sample": self.phase_dir(ContentPhase.MAIN_MENU)
            / "setup"
            / "start"
            / "10_countries.txt",
            "main_menu_location_setup_sample": self.phase_dir(ContentPhase.MAIN_MENU)
            / "setup"
            / "start"
            / "21_locations.txt",
            "loading_screen_localization_sample": self.phase_dir(ContentPhase.LOADING_SCREEN)
            / "localization"
            / "english"
            / "load_tips_l_english.yml",
            "map_default": self.phase_dir(ContentPhase.IN_GAME) / "map_data" / "default.map",
            "map_definitions": self.phase_dir(ContentPhase.IN_GAME)
            / "map_data"
            / "definitions.txt",
            "map_adjacencies": self.phase_dir(ContentPhase.IN_GAME)
            / "map_data"
            / "adjacencies.csv",
            "map_ports": self.phase_dir(ContentPhase.IN_GAME) / "map_data" / "ports.csv",
            "localization_sample": self.phase_dir(ContentPhase.MAIN_MENU)
            / "localization"
            / "english"
            / "actions_l_english.yml",
            "dlc_metadata": self.dlc_dir / "D000_shared" / "D000_shared.dlc.json",
        }
